### ISSUE TITLE
`vehicle.xsd` ambigous content model

### ISSUE THREAD

**Issue by LukeV1** [Marsfan/Farming-Simulator-Mod-Doc#11]
## Details
I just started to learn about xml validation with xsd files and created a quick c# project therefore. Unfortunately VisualStudio just came up with the following error message:

> Mehrere Definitionen des Elements 'dashboard' verursachen ein mehrdeutiges Inhaltsmodell. Ein Inhaltsmodell muss so gebildet werden, dass während der Validierung einer Elementinformationssequenz das darin direkt, indirekt oder implizit enthaltene Partikel, mit dem versucht wird, jedes Element in der Sequenz zu validieren, wiederum eindeutig bestimmt werden kann, ohne den Inhalt oder die Attribute dieses Elements zu untersuchen und ohne dass beliebige Informationen zu den Elementen im Rest der Sequenz benötigt werden.

In english:

> Multiple definitions of the dashboard element cause an ambiguous content model. A content model must be formed in such a way that, during the validation of an element information sequence, the particle directly, indirectly or implicitly contained in it, with which it is attempted to validate each element in the sequence, can in turn be uniquely determined without the content or the attributes of this element to investigate and without needing any information about the elements in the rest of the sequence.

## Location
`vehicle.xsd` line 285

## Proposed Correction (if relevant)
I'm an absolute beginner concerning xsd files, don't have any clue...

## Proof (if relevant)
Just open the file in Visual Studio and it will complain right away.

**Comment by Marsfan** [comment]
That's odd. I'll try to take a look at it this weekend. What version of VisualStudio are you using?

**Comment by LukeV1** [comment]
I'm using VisualStudio 2015 community edition

**Comment by Marsfan** [comment]
Ok. I think I fixed the issue. There appeared to be a duplicate definition of the `dashboard` type. Let me know if it looks good on your end.

**Comment by LukeV1** [comment]
Yes, now VS2015 likes it.
Thanks a lot!
