### ISSUE TITLE
Fix GitHub not detecting requirements.txt

### ISSUE THREAD

**Issue by Marsfan** [Marsfan/Farming-Simulator-Mod-Doc#2]
For some reason, the dependency graph feature on GitHub is not properly detecting any of the `requirements.txt` files in the repository, and as such is leaving the dependency graph empty. 

This should ideally be solved, so that we can start using version locking with requirements.txt and relying on dependabot to check and update the dependencies.

**Comment by Marsfan** [comment]
Dependencies from `utils/requirements.txt` seem to be populating now. It is possible that the dependency tracker is just a little bit slow. Keeping issue open until dependencies from `docs/requirements.txt` also populates.

**Comment by LukeV1** [comment]
Seems to be solved? 😉

**Comment by Marsfan** [comment]
Neat
